version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.9"
  jobs:
    pre_build:
      - pip install -U pip
      - conda env create -f environment.yml
    build:
      - conda run -n computing-in-context jupyter-book build .